---
- hosts: all
  remote_user: vagrant
  sudo: yes
  gather_facts: no
  vars:
    private_ntpserver: 10.7.20.30
  tasks:

  - name: Deploy NTPD services
    apt: name=ntp state=installed update_cache=yes

  - name: Deploy ntp.conf
    template: 
      src: /home/vagrant/ansible-repo/files/ntp.conf.j2 
      dest: /etc/ntp.conf mode=644 owner=root group=root
    notify: restart ntp

  - name: Start ntpd 
    service: name=ntp state=started

  handlers:

  - name: Restart ntpd
    service: name=ntp state=restarted
