#Deploy web farm
- hosts: webservers
  sudo: yes

  tasks:

  - name: install nginx
    apt: name=nginx state=installed

  - name: write our nginx.conf
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: write our /etc/nginx/sites-available/default
    template: src=templates/default-site.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: deploy website content
    template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

#Setup failover on load balancers
- hosts: elb
  sudo: yes
  gather_facts: yes
  vars:
     worker: "{{ ohai_hostname }}"

  tasks:
  - name: Deploy keepalived
    apt: name=keepalived state=installed
  # sysctl.conf requirements for keepalive
  - sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present
  - sysctl: name="net.ipv4.ip_nonlocal_bind" value=1 sysctl_set=yes state=present

  - name: Deploying template configs (keepalived.conf)
    template:
      src: "templates/keepalived.conf.j2"
      dest: "/etc/keepalived/keepalived.conf"
    notify:
      - restart keepalived
  - name: Ensure keepalive is running (and enable it at boot)
    service: name=keepalived state=started enabled=yes
  handlers:
   - name: restart keepalived
     service: name=keepalived state=restarted

#setup haproxy on elbs
- hosts: elb
  sudo: yes
  gather_facts: yes
  tasks:

  - name: install haproxy and socat
    apt: pkg={{ item }} state=latest
    with_items:
    - haproxy
    - socat

  - name: enable haproxy
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify: restart haproxy

  - name: deploy haproxy config
    template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy
  - name: Ensure haproxy service is enabled and started
    service: name=haproxy state=started enabled=yes
  handlers:

  - name: restart haproxy
    service: name=haproxy state=restarted

